from __future__ import annotations

from .models import ReflectedType


def render_header(types: list[ReflectedType]) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/refl_codegen. Do not edit by hand.",
        "",
        "#include <tuple>",
        "",
        '#include "refl/refl.hpp"',
        "",
        "namespace refl {",
        "",
    ]

    for reflected in types:
        lines.append("template <>")
        lines.append(f"struct TypeInfo<{reflected.qualified_name}> {{")
        lines.append("    static consteval auto members() {")
        if reflected.fields:
            lines.append("        return std::make_tuple(")
            for index, field in enumerate(reflected.fields):
                suffix = "," if index + 1 < len(reflected.fields) else ""
                lines.append(
                    f'            Member{{"{field.name}", &{reflected.qualified_name}::{field.name}}}{suffix}'
                )
            lines.append("        );")
        else:
            lines.append("        return std::make_tuple();")
        lines.append("    }")
        lines.append("};")
        lines.append("")

    lines.append("} // namespace refl")
    lines.append("")
    return "\n".join(lines)
